### PR TITLE
new folders added

### PR DESCRIPTION
**Pull request by Goldmaster**
Hi there, I have added in a few new folders,

added screenshots which can be put into folders as name of a game or program,

added plugins folder for sketchup or any other plugins such as web browsers.

will add new options as they go.

### CODE REVIEW

**Comment by Teraskull** [comment]
Why did you delete all of the README and gitkeep files?
And also added a useless Windows.iso placeholder.

Why do you need a separate "Created memes" folder, if "memes" is enough? Same with the videos folder.

A lot of typos in placeholders and folder names.

If this works for you, great, but it's not something worth merging here.

**Comment by Goldmaster** [comment]
> Why did you delete all of the README and gitkeep files?
>
gitkeep and readme files are still there
> And also added a useless Windows.iso placeholder.
>
That's to demonstrate where isos would be saved to
> 
> Why do you need a separate "Created memes" folder, if "memes" is enough? Same with the videos folder.
>
so that you know which videos have been downloaded from the internet and which videos you created yourself. If I created a video for youtube, does it go in the youtube folder or what? when the video would also go to Vimeo? 
> A lot of typos in placeholders and folder names.
>
example?
> If this works for you, great, but it's not something worth merging here.
>
cant you merge selected parts?

**Comment by Teraskull** [comment]
> example?

"catagories", "downlaoded", "Pluggins".

> so that you know which videos have been downloaded from the internet and which videos you created yourself

Again, if someone needs separate folders for memes or videos, they will create them themself. No need to have stuff like that in a template repo.

> cant you merge selected parts?

I can't merge, but even if I could, there is still nothing important for a template here.

**Comment by Goldmaster** [comment]
@Teraskull the issues, you have mentioned, have been fixed.

**Comment by Teraskull** [comment]
@Goldmaster I doubt these changes will be merged, since the repo is pretty stale, but yes, in my opinion, these folders are way to specific and hoarders should decide themselves if they need them.

**Comment by roboyoshi** [comment]
Unfortunately I have to close this - the additions are in good faith, I assume, but the quality/consistency is not in line with what I have in mind here. As teraskull mentioned, it's a bit too specific and I think should be left as an exercise to the end-user.

**Pull request closed without merging**
